name: Lint and Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)  # see: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-output-parameter-set-output
      id: nvm
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: npm install
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Setup pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Unit Testing
      run: |
        cd content-repo
        pipenv run pytest -v
